version: '3'

services:
  tomcat-service:
    image: tomcat:9
    ports:
      - "8080:8080"
    volumes:
      - "/mnt/wars:/usr/local/tomcat/webapps"
    networks:
      - velocity

  mysql_db:
    image: mysql:8.0.28
    container_name: velocity     
    volumes:
      - ./init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: USER
    networks:
      - velocity                        

networks:
  velocity:
    driver: bridge
